#! /bin/zsh
# vim:ft=zsh

autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
PROMPT='%B%F{blue}%3~%f%b %_%# '
RPROMPT=\$vcs_info_msg_0_
zstyle ':vcs_info:git:*' formats '%F{green}(%b) %r/%S%f'
zstyle ':vcs_info:*' enable git

